global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - "192.168.10.2:9100"
          - "192.168.10.3:9100"

  - job_name: 'nginx'
    static_configs:
      - targets: []
