# provisioning/roles/node_exporter/tasks/main.yml
---
- name: Instalar node_exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true
  become: true
- name: Asegurar node_exporter corriendo
  service:
    name: prometheus-node-exporter
    state: started
    enabled: tr
