- name: Instalar dependencias JMeter
  apt:
    name:
      - default-jre
      - wget
      - tar
    state: present
    update_cache: yes

- name: Descargar Apache JMeter
  get_url:
    url: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
    dest: /opt/apache-jmeter-5.6.3.tgz
    mode: "0644"
  args:
    creates: /opt/apache-jmeter-5.6.3.tgz

- name: Descomprimir JMeter
  unarchive:
    src: /opt/apache-jmeter-5.6.3.tgz
    dest: /opt
    remote_src: true
    creates: /opt/apache-jmeter-5.6.3

- name: Crear symlink a jmeter
  file:
    src: /opt/apache-jmeter-5.6.3/bin/jmeter
    dest: /usr/local/bin/jmeter
    state: link

- name: Crear directorio de pruebas JMeter
  file:
    path: /opt/jmeter/tests
    state: directory
    mode: "0755"

- name: Copiar plan de prueba JMeter
  copy:
    src: dataexplorer-nginx.jmx
    dest: /opt/jmeter/tests/dataexplorer-nginx.jmx
    mode: "0644"
