# provisioning/group_vars/all.yml
nginx_listen_port: 80
# Prometheus/Grafana puertos
prometheus_port: 9090
grafana_port: 3000
# Node exporter puertos (por defecto: 9100)
node_exporter_port: 9100
# Targets de Node Exporter (IPs de server y monitor)
prometheus_targets_node_exporter:
  - "192.168.10.2:9100"
  - "192.168.10.3:9100"
# (Opcional) si agregas nginx-prometheus-exporter en 'server', define targets:
prometheus_targets_nginx: [] # p.ej.: ["192.168.10.2:9113"]
